language: objective-c

before_install:
- export LANG=en_US.UTF-8
- gem install cocoapods
- brew update
- if brew outdated | grep -qx xctool; then brew upgrade xctool; fi

script: 
- xctool clean build test -workspace JSNCardStack.xcworkspace -scheme JSNCardStack -sdk iphonesimulator8.1 ONLY_ACTIVE_ARCH=NO
